#!/data/data/com.termux/files/usr/bin/bash
# Recurring reconciler: re-apply dns-doh wrapper patch when missing.
# The claude wrapper can be regenerated by a full CLI reinstall (write_wrappers()
# in vendor/claude-install.sh), wiping the patch. This reconciler reapplies it.
set -euo pipefail
HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "$HERE/../lib.sh"

_DOH_SO="$HOME/claude-code-android/dns-doh/dohshim.so"
_CLAUDE_WRAPPER="$HOME/claude-code-android/bin/claude"

[ -f "$_DOH_SO" ]           || exit 0
[ -f "$_CLAUDE_WRAPPER" ]   || exit 0
grep -qF '# >>> dns-doh shim >>>' "$_CLAUDE_WRAPPER" && exit 0

log "dns-doh installed but wrapper patch missing — re-applying"
bash "$HERE/../install-dns-doh.sh" --patch-only
