#!/data/data/com.termux/files/usr/bin/bash
# Shared helpers for bootstrap scripts.
# Source this file: source "$(dirname "$0")/lib.sh"

set -euo pipefail

if [ -t 1 ]; then
    C_RED=$'\033[0;31m'; C_GRN=$'\033[0;32m'; C_YEL=$'\033[1;33m'
    C_BLU=$'\033[0;34m'; C_BLD=$'\033[1m'; C_NC=$'\033[0m'
else
    C_RED=''; C_GRN=''; C_YEL=''; C_BLU=''; C_BLD=''; C_NC=''
fi

log()  { printf '%s[bootstrap]%s %s\n' "$C_BLU" "$C_NC" "$*"; }
ok()   { printf '%s[ok]%s %s\n' "$C_GRN" "$C_NC" "$*"; }
warn() { printf '%s[warn]%s %s\n' "$C_YEL" "$C_NC" "$*" >&2; }
die()  { printf '%s[err]%s %s\n' "$C_RED" "$C_NC" "$*" >&2; exit 1; }

require_termux() {
    [ "${PREFIX:-}" = "/data/data/com.termux/files/usr" ] \
        || die "Not running inside Termux (PREFIX=$PREFIX). Install Termux from F-Droid first."
    [ "$(uname -m)" = "aarch64" ] \
        || die "Unsupported arch $(uname -m). Only aarch64 Android is supported."
}

# ── Optional add-on projects ────────────────────────────────────────────────
# Registry of optional projects installable on demand via `cc install <name>`.
# Each is cloned into ~/cc-projects, tagged CC-Dev, and (if it ships a
# package.json) npm-installed. This table is the single source of truth — the
# installer, the updater, and the `cc install` listing all read from it.
# One row per project, tab-separated: <canonical-name> <git-url> <description>
optional_projects_table() {
    printf '%s\t%s\t%s\n' \
        code-share \
        "https://github.com/UnmanagedCode/code-share.git" \
        "Peer-to-peer read-only Git repo sharing over LAN/internet (web UI :9420)"
    printf '%s\t%s\t%s\n' \
        termux-playwright-harness \
        "https://github.com/UnmanagedCode/termux-playwright-harness.git" \
        "Playwright + Termux-Chromium glue for visual UI debugging from a phone"
    printf '%s\t%s\t%s\n' \
        dns-doh \
        "" \
        "DNS-over-HTTPS fallback for Claude on captive/hotel networks (LD_PRELOAD shim)"
}

# Print every optional project's canonical name, one per line.
optional_project_names() { optional_projects_table | cut -f1; }

# Map a user-given name (or short alias) to its canonical name on stdout.
# Returns 1 if the name isn't a known optional project.
canonical_optional_project() {
    case "$1" in
        code-share|codeshare|share)                   echo code-share ;;
        playwright|harness|termux-playwright-harness)  echo termux-playwright-harness ;;
        dns-doh|doh-dns|doh)                           echo dns-doh ;;
        *) return 1 ;;
    esac
}

# Print the git URL for a canonical optional-project name. Returns 1 if unknown.
optional_project_url() {
    optional_projects_table \
        | awk -F'\t' -v n="$1" '$1==n {print $2; found=1} END {exit !found}'
}

# ── dns-doh shim wrapper patch ──────────────────────────────────────────────
# Single source of truth for the dns-doh marker block, shared by
# install-dns-doh.sh (post-hoc patch of an existing wrapper) and
# vendor/claude-install.sh's write_wrappers() (bakes the block in at
# generation time so a regenerated wrapper is never observably unpatched).
DOH_MARKER_START='# >>> dns-doh shim >>>'
DOH_MARKER_END='# <<< dns-doh shim <<<'

# Echo the dns-doh shim block. $1: absolute path to dohshim.so.
dns_doh_shim_block() {
    printf '%s\n' "$DOH_MARKER_START"
    printf '_DOH_SHIM="%s"\n' "$1"
    printf '[ -f "$_DOH_SHIM" ] && export LD_PRELOAD="$_DOH_SHIM"\n'
    printf '%s\n' "$DOH_MARKER_END"
}

# Filter (stdin -> stdout): insert dns_doh_shim_block($1) immediately after
# the first `unset LD_PRELOAD` line. Callers must only invoke this on content
# that isn't already patched (both current callers already guard on that).
# $1: absolute path to dohshim.so.
dns_doh_insert_block() {
    local block
    block="$(dns_doh_shim_block "$1")"
    awk -v block="$block" '
        /^unset LD_PRELOAD$/ && !done {
            print
            print ""
            print block
            done=1
            next
        }
        { print }
    '
}

# Echo the bin/claude-mux multiplexer shim script. Claude Code's Bash-tool
# grep/find shell functions run `exec -a ugrep "$CLAUDE_CODE_EXECPATH" -G ...`
# and `exec -a bfs "$CLAUDE_CODE_EXECPATH" -S dfs ...`; dohshim repoints
# CLAUDE_CODE_EXECPATH (off the ld.so path) at this shim in the child env.
# Shared by write_wrappers() (vendor/claude-install.sh) and the reconcile
# migration so both emit byte-identical content.
# $1: bash interpreter (shebang), $2: glibc ld.so, $3: glibc libdir,
# $4: absolute path to claude.exe.
claude_mux_wrapper() {
    printf '#!%s\n' "$1"
    cat <<'MUX_BODY'
# Auto-generated by claude-code-android — do not edit by hand.
# Multiplexer shim for Claude Code's Bash-tool grep/find shell functions, which
# invoke it as:  exec -a ugrep <this> -G ...   and   exec -a bfs <this> -S dfs ...
# argv[0] is lost through `exec -a NAME script`, so dispatch on the leading flag
# the snapshot always prepends, then re-exec claude.exe via ld.so with argv[0]
# set to ugrep/bfs/rg so grep and find hit claude's bundled ripgrep/bfs.
unset LD_PRELOAD
export RES_OPTIONS="${RES_OPTIONS:-use-vc}"
case "${1:-}" in
    -S) _a0=bfs ;;
    -G) _a0=ugrep ;;
    *)  _a0=rg ;;
esac
MUX_BODY
    printf 'exec "%s" --library-path "%s" --argv0 "$_a0" "%s" "$@"\n' "$2" "$3" "$4"
}
